# Generated by Django 3.2.8 on 2021-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211105_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_slug',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
