# Generated by Django 3.2.8 on 2021-11-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211128_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='response',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
